package com.scor.rr.metrics;

/**
 * Metric Statics
 * 
 * @author HADDINI Zakariyae
 *
 */
public class MetricStatics {

	public static final String JSON_DATA_01_KPI_SEARCH_WITH_QUALIFIER = "  {                                          "
			+ "  \"query\": {                               " + "  \"bool\": {                                "
			+ "  \"must\": [                                " + "    {\"match\": {\"qualifier\":\"XXXX\"}},   "
			+ "    {\"match\": {\"environnement\":\"DEV\"}} " + "    ]                                        "
			+ "}                                            " + "}                                            "
			+ "}                                            " + "  ";

	public static final String JSON_DATA_01b_KPI_SEARCH_WITH_QUALIFIER_AND_RETROACTIV_CODE = "  {                                          "
			+ "  \"query\": {                                                        "
			+ "  \"bool\": {                                                         "
			+ "  \"must\": [                                                         "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},                            "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},                         "
			+ "    {\"range\": {\"@timestamp\":{\"from\":\"now-1[YYYY]/[YYYY]\" }}}  "
			+ "    ]                                                                 "
			+ "}                                                                     "
			+ "}                                                                     "
			+ "}                                                                     " + "  ";

	public static final String JSON_DATA_01c_KPI_SEARCH_WITH_QUALIFIER_AND_CORROLATION_ID = "  {                                          "
			+ "  \"query\": {                                     "
			+ "  \"bool\": {                                      "
			+ "  \"must\": [                                      "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},         "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},      "
			+ "    {\"match\": {\"meta.CorrelationId\":\"ZZZZ\"}} "
			+ "    ]                                              "
			+ "}                                                  "
			+ "}                                                  "
			+ "}                                                  " + "  ";

	public static final String JSON_DATA_01d_KPI_SEARCH_WITH_QUALIFIER_RETROACTIV_CODE_AND_STATUS = "  {                                          "
			+ "  \"query\": {                                                        "
			+ "  \"bool\": {                                                         "
			+ "  \"must\": [                                                         "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},                            "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},                         "
			+ "    {\"match\": {\"meta.Status\":\"ZZZZ\"}}, "
			+ "    {\"range\": {\"@timestamp\":{\"from\":\"now-1[YYYY]/[YYYY]\" }}}  "
			+ "    ]                                                                 "
			+ "}                                                                     "
			+ "}                                                                     "
			+ "}                                                                     " + "  ";

	public static final String JSON_DATA_01e_KPI_SEARCH_WITH_QUALIFIER_AND_STATUS = "  {                                          "
			+ "  \"query\": {                                                        "
			+ "  \"bool\": {                                                         "
			+ "  \"must\": [                                                         "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},                            "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},                         "
			+ "    {\"match\": {\"meta.Status\":\"ZZZZ\"}} "
			+ "    ]                                                                 "
			+ "}                                                                     "
			+ "}                                                                     "
			+ "}                                                                     " + "  ";

	public static final String JSON_DATA_02_KPI_SEARCH_VALUE_WITH_QUALIFIER = "  {                                          "
			+ "  \"fields\": [\"value\"]                    " + "  \"query\": {                               "
			+ "  \"bool\": {                                " + "  \"must\": [                                "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},   " + "    {\"match\": {\"environnement\":\"DEV\"}} "
			+ "    ]                                        " + "}                                            "
			+ "}                                            " + "}                                            " + "  ";

	public static final String JSON_DATA_03_KPI_AGGREG_VALUES_WITH_AND_STATUS = "  {                                          "
			+ "  \"query\": {                                  " + "  \"bool\": {                                   "
			+ "  \"must\": [                                   " + "    {\"match\": {\"qualifier\":\"XXXX\"}},      "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},   " + "    {\"match\": {\"meta.Status\":\"ZZZZ\"}}     "
			+ "    ]                                           " + "}                                               "
			+ "} ,  \"size\": 0,                               " + "                                                "
			+ "  \"aggs\" : {                                  " + "  \"hit_over_time\" : {                         "
			+ "  \"date_histogram\" : {                        " + "  \"field\" : \"@timestamp\",                   "
			+ "  \"interval\" : \"YYYY\"                       " + " }                                              "
			+ " }                                              " + " }                                              "
			+ " }                                              " + "                                                ";

	public static final String JSON_DATA_04_KPI_AGGREG_VALUES_WITH_STATUS_AND_RETROACTIV = "  {                                          "
			+ "  \"query\": {                                  " + "  \"bool\": {                                   "
			+ "  \"must\": [                                   " + "    {\"match\": {\"qualifier\":\"XXXX\"}},      "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},   " + "    {\"match\": {\"meta.Status\":\"ZZZZ\"}},     "
			+ "    {\"range\": {\"@timestamp\":{\"from\":\"now-1[UUUU]/[UUUU]\" }}}  "
			+ "    ]                                           " + "}                                               "
			+ "} ,  \"size\": 0,                               " + "                                                "
			+ "  \"aggs\" : {                                  " + "  \"hit_over_time\" : {                         "
			+ "  \"date_histogram\" : {                        " + "  \"field\" : \"@timestamp\",                   "
			+ "  \"interval\" : \"YYYY\"                       " + " }                                              "
			+ " }                                              " + " }                                              "
			+ " }                                              " + "                                                ";

	public static final String JSON_DATA_05_HIT_KPI_AGGREG_VALUES_BY = "  {                                          "
			+ "  \"query\": {                                  " + "  \"bool\": {                                   "
			+ "  \"must\": [                                   " + "    {\"match\": {\"qualifier\":\"XXXX\"}},      "
			+ "    {\"match\": {\"environnement\":\"DEV\"}}    " + "    ]                                           "
			+ "}                                               " + "} ,  \"size\": 0,                               "
			+ "                                                " + "  \"aggs\" : {                                  "
			+ "  \"hit_over_time\" : {                         " + "  \"date_histogram\" : {                        "
			+ "  \"field\" : \"@timestamp\",                   " + "  \"interval\" : \"YYYY\"                       "
			+ " }                                              " + " }                                              "
			+ " }                                              " + " }                                              "
			+ "                                                ";

	public static final String JSON_DATA_06_HIT_KPI_AGGREG_VALUES_BY_AND_RETROACTIV = "  {                                          "
			+ "  \"query\": {                                                           "
			+ "  \"bool\": {                                                            "
			+ "  \"must\": [                                                            "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},                               "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},                            "
			+ "    {\"range\": {\"@timestamp\":{\"from\":\"now-1[UUUU]/[UUUU]\" }}}     "
			+ "    ]                                                                    "
			+ "}                                                                        "
			+ "} ,  \"size\": 0,                                                        "
			+ "                                                                         "
			+ "  \"aggs\" : {                                                           "
			+ "  \"hit_over_time\" : {                                                  "
			+ "  \"date_histogram\" : {                                                 "
			+ "  \"field\" : \"@timestamp\",                                            "
			+ "  \"interval\" : \"YYYY\"                                                "
			+ " }                                                                       "
			+ " }                                                                       "
			+ " }                                                                       "
			+ " }                                                                       "
			+ "                                                                         ";

	public static final String JSON_DATA_07_VALUE_KPI_AGGREG_BY_TOTAL_VALUE = "  {                                          "
			+ "  \"query\": {                                                           "
			+ "  \"bool\": {                                                            "
			+ "  \"must\": [                                                            "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},                               "
			+ "    {\"match\": {\"environnement\":\"DEV\"}}                             "
			+ "    ]                                                                    "
			+ "}                                                                        "
			+ "} ,  \"size\": 0,                                                        "
			+ "                                                                         "
			+ "  \"aggs\":{                                                             "
			+ "  \"hit_over_time\" : {                                                  "
			+ "  \"date_histogram\" : {                                                 "
			+ "  \"field\" : \"@timestamp\",                                            "
			+ "  \"interval\" : \"YYYY\"                                                "
			+ " },                                                                      "
			+ " \"aggs\" : {                                                            "
			+ "    \"total\": { \"sum\" : { \"field\" : \"value\" } }                   "
			+ "       }                                                                 "
			+ " }                                                                       "
			+ " }                                                                       "
			+ " }                                                                       "
			+ "                                                                         ";

	public static final String JSON_DATA_08_VALUE_KPI_AGGREG_BY_TOTAL_VALUE_AND_RETROACTIV = "  {                                          "
			+ "  \"query\": {                                                           "
			+ "  \"bool\": {                                                            "
			+ "  \"must\": [                                                            "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},                               "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},                            "
			+ "    {\"range\": {\"@timestamp\":{\"from\":\"now-1[UUUU]/[UUUU]\" }}}     "
			+ "    ]                                                                    "
			+ "}                                                                        "
			+ "} ,  \"size\": 0,                                                        "
			+ "                                                                         "
			+ "  \"aggs\":{                                                             "
			+ "  \"hit_over_time\" : {                                                  "
			+ "  \"date_histogram\" : {                                                 "
			+ "  \"field\" : \"@timestamp\",                                            "
			+ "  \"interval\" : \"YYYY\"                                                "
			+ " },                                                                      "
			+ " \"aggs\" : {                                                            "
			+ "    \"total\": { \"sum\" : { \"field\" : \"value\" } }                   "
			+ "       }                                                                 "
			+ " }                                                                       "
			+ " }                                                                       "
			+ " }                                                                       "
			+ "                                                                         ";

	public static final String JSON_DATA_09_VALUE_KPI_AGGREG_BY_AVERAGE_VALUE = "  {                                          "
			+ "  \"query\": {                                                           "
			+ "  \"bool\": {                                                            "
			+ "  \"must\": [                                                            "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},                               "
			+ "    {\"match\": {\"environnement\":\"DEV\"}}                             "
			+ "    ]                                                                    "
			+ "}                                                                        "
			+ "} ,  \"size\": 0,                                                        "
			+ "                                                                         "
			+ "  \"aggs\":{                                                             "
			+ "  \"hit_over_time\" : {                                                  "
			+ "  \"date_histogram\" : {                                                 "
			+ "  \"field\" : \"@timestamp\",                                            "
			+ "  \"interval\" : \"YYYY\"                                                "
			+ " },                                                                      "
			+ " \"aggs\" : {                                                            "
			+ "    \"moyenne\": { \"avg\" : { \"field\" : \"value\" } }                   "
			+ "       }                                                                 "
			+ " }                                                                       "
			+ " }                                                                       "
			+ " }                                                                       "
			+ "                                                                         ";

	public static final String JSON_DATA_10_VALUE_KPI_AGGREG_BY_AVERAGE_VALUE_AND_RETROACTIV = "  {                                          "
			+ "  \"query\": {                                                           "
			+ "  \"bool\": {                                                            "
			+ "  \"must\": [                                                            "
			+ "    {\"match\": {\"qualifier\":\"XXXX\"}},                               "
			+ "    {\"match\": {\"environnement\":\"DEV\"}},                            "
			+ "    {\"range\": {\"@timestamp\":{\"from\":\"now-1[UUUU]/[UUUU]\" }}}     "
			+ "    ]                                                                    "
			+ "}                                                                        "
			+ "} ,  \"size\": 0,                                                        "
			+ "                                                                         "
			+ "  \"aggs\":{                                                             "
			+ "  \"hit_over_time\" : {                                                  "
			+ "  \"date_histogram\" : {                                                 "
			+ "  \"field\" : \"@timestamp\",                                            "
			+ "  \"interval\" : \"YYYY\"                                                "
			+ " },                                                                      "
			+ " \"aggs\" : {                                                            "
			+ "    \"moyenne\": { \"avg\" : { \"field\" : \"value\" } }                   "
			+ "       }                                                                 "
			+ " }                                                                       "
			+ " }                                                                       "
			+ " }                                                                       "
			+ "                                                                         ";

}