

export const ADJUSTMENTS_ARRAY= [
  {
    "id": 1,
    "adjustmentBasis": "Wind Pool",
    "category": "Base",
    "name": "Wind Pool",
    "description": "An adjustment to be applied on the basis that wind pools may relieve or contribute to losses.",
    "exposureFlag": "UNCAPPED",
    "sequence": 13,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 1
  },
  {
    "id": 2,
    "adjustmentBasis": "Allocated Loss Adjustment Expense (ALAE)",
    "category": "Client",
    "name": "ALAE",
    "description": "An adjustment to be applied on the basis that losses are expected to be higher than anticipated due to legal costs, business costs, and other associated losses outside of the exposures themselves.",
    "exposureFlag": "UNCAPPED",
    "sequence": 7,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 2
  },
  {
    "id": 4,
    "adjustmentBasis": "Exposure Adjustment (Portfolio Evolution)",
    "category": "Base",
    "name": "Portfolio Evolution",
    "description": "An adjustment to be applied on the basis that exposure is expected to grow or shrink for a client.",
    "exposureFlag": "UNCAPPED",
    "sequence": 1,
    "isExposureGrowth": true,
    "value": "2,1",
    "idAdjustementType": 4
  },
  {
    "id": 5,
    "adjustmentBasis": "Missing Exposure",
    "category": "Base",
    "name": "Missing Exposures",
    "description": "An adjustment to be applied on the basis that exposure is believed to be missing from the client's data.",
    "exposureFlag": "UNCAPPED",
    "sequence": 2,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 5
  },
  {
    "id": 6,
    "adjustmentBasis": "Cedant Historical Claims",
    "category": "Client",
    "name": "Cedant Claims",
    "description": "An adjustment to be applied on the basis of client claims data (contextualization).",
    "exposureFlag": "CAP",
    "sequence": 11,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 6
  },
  {
    "id": 7,
    "adjustmentBasis": "Demand Surge Or Post-Loss Amplification",
    "category": "Base",
    "name": "Post-Loss Amp",
    "description": "An adjustment to be applied on the basis that losses are amplified by post event factors (e.g. lumber costs increase).",
    "exposureFlag": "CAP",
    "sequence": 15,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 7
  },
  {
    "id": 8,
    "adjustmentBasis": "Fire Following Earthquake",
    "category": "Base",
    "name": "Fire Following",
    "description": "An adjustment to be applied on the basis that fire losses are not reflective of the SCOR or analysts' views.",
    "exposureFlag": "CAP",
    "sequence": 17,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 8
  },
  {
    "id": 9,
    "adjustmentBasis": "Storm Surge",
    "category": "Base",
    "name": "Storm Surge",
    "description": "An adjustment to be applied on the basis that flooding losses are not reflective of the SCOR or analysts' views.",
    "exposureFlag": "CAP",
    "sequence": 16,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 9
  },
  {
    "id": 10,
    "adjustmentBasis": "Hours Clause",
    "category": "Client",
    "name": "Hours Clause",
    "description": "An adjustment to be applied on the basis that an hours clause has modified losses.",
    "exposureFlag": "CAP",
    "sequence": 12,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 10
  },
  {
    "id": 14,
    "adjustmentBasis": "Cedant \"Quality Index\" (QI)",
    "category": "Client",
    "name": "Cedant QI",
    "description": "An adjustment to be applied on the basis of a client rating index.",
    "exposureFlag": "CAP",
    "sequence": 3,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 14
  },
  {
    "id": 15,
    "adjustmentBasis": "Hazardous Waste Removal",
    "category": "Client",
    "name": "Haz. Waste Removal",
    "description": "An adjustment to be applied on the basis of risk being under or overstated.",
    "exposureFlag": "CAP",
    "sequence": 21,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 15
  },
  {
    "id": 16,
    "adjustmentBasis": "Loss Inflation due to Political Pressure",
    "category": "Client",
    "name": "Political Pressure",
    "description": "An adjustment to be applied on the basis of risk being under or overstated.",
    "exposureFlag": "CAP",
    "sequence": 23,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 16
  },
  {
    "id": 17,
    "adjustmentBasis": "Indirect Business Interruption",
    "category": "Client",
    "name": "Indirect BI",
    "description": "An adjustment to be applied on the basis of business interruption risk being under or overstated.",
    "exposureFlag": "CAP",
    "sequence": 14,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 17
  },
  {
    "id": 18,
    "adjustmentBasis": "Replacement Values (RV) Underestimation",
    "category": "Client",
    "name": "RV Underestimation",
    "description": "An adjustment to be applied on the basis of replacement values believed to be understated.",
    "exposureFlag": "UNCAPPED",
    "sequence": 8,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 18
  },
  {
    "id": 19,
    "adjustmentBasis": "Replacement Values (RV) Overestimation",
    "category": "Client",
    "name": "RV Overestimation",
    "description": "An adjustment to be applied on the basis of replacement values believed to be overstated.",
    "exposureFlag": "UNCAPPED",
    "sequence": 9,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 19
  },
  {
    "id": 20,
    "adjustmentBasis": "High % Unknown Primary Modifiers (e.g. Uncertainty Loading)",
    "category": "Client",
    "name": "Unknown Primary Mod.",
    "description": "An adjustment to be applied on the basis of risk being under or overstated.",
    "exposureFlag": "CAP",
    "sequence": 4,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 20
  },
  {
    "id": 21,
    "adjustmentBasis": "Missing Critical Primary Characteristics (Unknown Floor Level For Flood)",
    "category": "Client",
    "name": "Missing Primary Char.",
    "description": "An adjustment to be applied on the basis of risk being under or overstated.",
    "exposureFlag": "CAP",
    "sequence": 5,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 21
  },
  {
    "id": 24,
    "adjustmentBasis": "Looting",
    "category": "Client",
    "name": "Looting",
    "description": "An adjustment to be applied on the basis of risk being under or overstated.",
    "exposureFlag": "CAP",
    "sequence": 24,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 24
  },
  {
    "id": 25,
    "adjustmentBasis": "Other Consequential Losses",
    "category": "Client",
    "name": "Other Conseq. Losses",
    "description": "An adjustment to be applied on the basis of risk being under or overstated.",
    "exposureFlag": "CAP",
    "sequence": 22,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 25
  },
  {
    "id": 26,
    "adjustmentBasis": "Simple Inuring",
    "category": "Inuring",
    "name": "Simple Inuring",
    "description": "An adjustment representative of Quota Share or Cat XL inuring.",
    "exposureFlag": "CAP",
    "sequence": 27,
    "isExposureGrowth": false,
    "value": "2,1",
    "idAdjustementType": 26
  }
].map(item => ({...item, linear: false, hover: false}) );
