package almf.rules

import com.scor.rr.importBatch.businessrules.bean.BusinessRulesBean;
import com.scor.rr.importBatch.processing.domain.loss.CMBetaConvertFunctionFactory;

rule "convertFunctionBeta"
      when
         $businessRulesBean : BusinessRulesBean( $map:inputData["petTransformFunction"] == "INV_BETA" && inputData["petType"] == "Quantile" )
      then
          modify ($businessRulesBean) {setOutputData("convertFunctionFactory",new CMBetaConvertFunctionFactory())}
end