package almf.rules

import com.scor.rr.importBatch.businessrules.bean.BusinessRulesBean;

rule "truncationThresholdELT"
      when
         $businessRulesBean : BusinessRulesBean( $map:inputData["lossTableType"] == "ELT" )
      then
          modify ($businessRulesBean) {setOutputData("threshold",Long.valueOf(0))}
          modify ($businessRulesBean) {setOutputData("thresholdCCY","EUR")}
          modify ($businessRulesBean) {setOutputData("anchorCCY","USD")}
end

rule "truncationThresholdPLT"
      when
         $businessRulesBean : BusinessRulesBean( $map:inputData["lossTableType"] == "PLT" )
      then
          modify ($businessRulesBean) {setOutputData("threshold",Long.valueOf(0))}
          modify ($businessRulesBean) {setOutputData("thresholdCCY","EUR")}
          modify ($businessRulesBean) {setOutputData("anchorCCY","USD")}
end