package almf.rules

import com.scor.rr.importBatch.businessrules.bean.BusinessRulesBean;

rule "activeChecksAccount"
     when
         $businessRulesBean : BusinessRulesBean( $map:inputData["jobType"] == "ACCOUNT" )
      then
          modify ($businessRulesBean) {setOutputData("EDMAvailableCheck",true)}
          modify ($businessRulesBean) {setOutputData("EDMPortfolioCheck",true)}
          modify ($businessRulesBean) {setOutputData("RequestIdCheck",false)}
          modify ($businessRulesBean) {setOutputData("LiabilityCurrencyCheck",true)}
          modify ($businessRulesBean) {setOutputData("BaseCurrencyCheck",true)}
          modify ($businessRulesBean) {setOutputData("BaseExchangeRateCheck",true)}
          modify ($businessRulesBean) {setOutputData("RDMAvailableCheck",true)}
          modify ($businessRulesBean) {setOutputData("RDMPortfolioCheck",true)}
          modify ($businessRulesBean) {setOutputData("AnalysisStatusCheck",true)}
          modify ($businessRulesBean) {setOutputData("ResultsReferencesExposureCheck",false)}
          modify ($businessRulesBean) {setOutputData("ModelledCurrencyCheck",true)}
          modify ($businessRulesBean) {setOutputData("MutuallyExclusiveProfilesCheck",true)}
          modify ($businessRulesBean) {setOutputData("OccupancyCodeCheck",false)}
          modify ($businessRulesBean) {setOutputData("ConstructionCodeCheck",true)}
          modify ($businessRulesBean) {setOutputData("EDMPortNumCheck",true)}
          modify ($businessRulesBean) {setOutputData("PortfolioCatCapacityCurrencyCheck",false)}
end

rule "activeChecksPortfolio"
     when
         $businessRulesBean : BusinessRulesBean( $map:inputData["jobType"] == "PORTFOLIO" )
      then
          modify ($businessRulesBean) {setOutputData("EDMAvailableCheck",true)}
          modify ($businessRulesBean) {setOutputData("EDMPortfolioCheck",true)}
          modify ($businessRulesBean) {setOutputData("RequestIdCheck",false)}
          modify ($businessRulesBean) {setOutputData("LiabilityCurrencyCheck",false)}
          modify ($businessRulesBean) {setOutputData("BaseCurrencyCheck",true)}
          modify ($businessRulesBean) {setOutputData("BaseExchangeRateCheck",true)}
          modify ($businessRulesBean) {setOutputData("RDMAvailableCheck",true)}
          modify ($businessRulesBean) {setOutputData("RDMPortfolioCheck",true)}
          modify ($businessRulesBean) {setOutputData("AnalysisStatusCheck",true)}
          modify ($businessRulesBean) {setOutputData("ResultsReferencesExposureCheck",false)}
          modify ($businessRulesBean) {setOutputData("ModelledCurrencyCheck",false)}
          modify ($businessRulesBean) {setOutputData("MutuallyExclusiveProfilesCheck",false)}
          modify ($businessRulesBean) {setOutputData("OccupancyCodeCheck",false)}
          modify ($businessRulesBean) {setOutputData("ConstructionCodeCheck",false)}
          modify ($businessRulesBean) {setOutputData("EDMPortNumCheck",true)}
          modify ($businessRulesBean) {setOutputData("PortfolioCatCapacityCurrencyCheck",true)}
end