import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.scss']
})
export class MainComponent implements OnInit {
  leftNavbarIsCollapsed:boolean = false;
  tabs = [ 1, 2, 3 ];
  constructor() {
    localStorage.setItem('pltData', JSON.stringify([
      {
        pltId: 1,
        systemTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        userTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        pathId: 1,
        pltName: "NATC-USM_RL_Imf.T1",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: false,
        note: true,
        checked: false
      },
      {
        pltId: 2,
        systemTags: [],
        userTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        pathId: 2,
        pltName: "NATC-USM_RL_Imf.T2",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: true,
        note: false,
        checked: true
      },
      {
        pltId: 3,
        systemTags: [{tagId: 1}, {tagId: 5}, {tagId: 7}],
        userTags: [{tagId: 3}],
        pathId: 3,
        pltName: "NATC-USM_RL_Imf.T3",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: false,
        note: false,
        checked: false
      },
      {
        pltId: 4,
        systemTags: [],
        userTags: [],
        pathId: 4,
        pltName: "NATC-USM_RL_Imf.T4",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: true,
        note: true,
        checked: true
      },
      {
        pltId: 5,
        systemTags: [{tagId: 1}, {tagId: 2}, {tagId: 5}],
        userTags: [{tagId: 1}, {tagId: 2}],
        pathId: 5,
        pltName: "NATC-USM_RL_Imf.T5",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: false,
        note: false,
        checked: false
      },
      {
        pltId: 6,
        systemTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        userTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        pathId: 1,
        pltName: "NATC-USM_RL_Imf.T6",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: true,
        note: true,
        checked: false
      },
      {
        pltId: 7,
        systemTags: [{tagId: 5}, {tagId: 7}, {tagId: 3}],
        userTags: [{tagId: 1}, {tagId: 2}],
        pathId: 2,
        pltName: "NATC-USM_RL_Imf.T7",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: true,
        note: true,
        checked: false
      },
      {
        pltId: 8,
        systemTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        userTags: [{tagId: 1}, {tagId: 2}],
        pathId: 3,
        pltName: "NATC-USM_RL_Imf.T8",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: false,
        note: true,
        checked: true
      },
      {
        pltId: 9,
        systemTags: [{tagId: 1}, {tagId: 5}, {tagId: 3}],
        userTags: [{tagId: 2}],
        pathId: 3,
        pltName: "NATC-USM_RL_Imf.T9",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: true,
        note: false,
        checked: false
      },
      {
        pltId: 10,
        systemTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        userTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        pathId: 2,
        pltName: "NATC-USM_RL_Imf.T10",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: false,
        note: true,
        checked: false
      },
      {
        pltId: 11,
        systemTags: [],
        userTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        pathId: 5,
        pltName: "NATC-USM_RL_Imf.T11",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: true,
        note: true,
        checked: false
      },
      {
        pltId: 12,
        systemTags: [{tagId: 5}, {tagId: 2}, {tagId: 7}],
        userTags: [{tagId: 2}, {tagId: 3}],
        pathId: 3,
        pltName: "NATC-USM_RL_Imf.T12",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: false,
        note: true,
        checked: true
      },
      {
        pltId: 13,
        systemTags: [{tagId: 1}, {tagId: 2}, {tagId: 3}],
        userTags: [{tagId: 1}, {tagId: 2}],
        pathId: 4,
        pltName: "NATC-USM_RL_Imf.T13",
        peril: "TC",
        regionPerilCode: "NATC-USM",
        regionPerilName: "North Atlantic",
        selected: false,
        grain: "liberty-NAHU",
        vendorSystem: "RMS RiskLink",
        rap: "North Atlantic",
        d: true,
        note: true,
        checked: false
      }

    ]))
  }

  ngOnInit() {
  }

}
